name: Build Rustpod

on:
  push:
    branches: [main]

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            artifact_name: rustpod
            asset_name: rustpod-linux-x86_64
          - os: macos-latest
            target: x86_64-apple-darwin
            artifact_name: rustpod
            asset_name: rustpod-macos-x86_64
          - os: macos-latest
            target: aarch64-apple-darwin
            artifact_name: rustpod
            asset_name: rustpod-macos-aarch64
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            artifact_name: rustpod.exe
            asset_name: rustpod-windows-x86_64.exe

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - name: Build
        run: cargo build --release --target ${{ matrix.target }}

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.asset_name }}
          path: target/${{ matrix.target }}/release/${{ matrix.artifact_name }}
